[project]
name = "docs-agent"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.136.1",
    "langchain>=0.3.30",
    "langchain-community>=0.3.31",
    "langgraph>=0.6.11",
    "langgraph-checkpoint-postgres>=3.1.0",
    "pgvector>=0.4.2",
    "psycopg2-binary>=2.9.12",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.1",
    "tqdm>=4.67.3",
    "uvicorn>=0.47.0",
]
